### ISSUE TITLE
Modular actions on People/Group lists

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/tenfour#107]
From tenfour-archive created by [caharding](https://github.com/caharding): ushahidi/tenfour-archive#1102  

As a user I want lists of groups and people to appear similarly throughout the application. I wan to be able to take actions on any list of people:
- [ ] I want to send a Check-in to any list of people or subset of that list
- [ ] I want to be able to save a list of people as a group 
- [ ] I want to be able to sort people alphabetically
- [ ] I want to be able to mass delete people with a confirm button
