### ISSUE TITLE
Chained Check-Ins

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/tenfour#140]
From tenfour-archive created by [caharding](https://github.com/caharding): ushahidi/tenfour-archive#1220  

### Expected behaviour
User expects to be able to send automatically send a check-in based off of someone's reply.
Example: Lucy send a message to her team: "Are you OK" and Xavier replies "No," she would like all "No" responses to receive a follow up message "Do you need medical attention?."

**Compose**
When composing a check-in, I expect to be able to have an option to link a new automatic check-in to a given response. I would expect an infinite amount of chains. 

**Dashboard**
I would expect to be able to see a list of all chains and how they are connected. I would expect to be able to travel up and down chains. 

### What's changing

- This would require us to extend the Check-in API 
- Would require a custom compose flow 
- Would require some sort of linking between Check-ins on the dashboard

### Actual behaviour
Check-ins don't have any logic written into them. 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Links to user stories, evidence and research to support the feature
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**User Research**
This issue came out of a team retreat UX session in The Hague. It was also requested by an experimental theater group.

**Comment by CeciliaHinga** [comment]
Request from the theatre group:

> I am really intrigued by Ushahidi but this TenFour seems like a good way to try out some things I want to do with a immersive theater group.
> 
> The idea is we have a sort of play going on but instead of on a stage where the director and actors all converse, people are spread about a part of town. We need to communicate with actors as well as audience members who will move about the "stage" and interact with different actors at certain points.
> 
> We're considering MightyText too but this wouldn't allow us to see any kind of data on canned replies (yes, no, 1, 2, 3 etc).
> 
> The holy grail here would be triggered messages. So if Sally replies Yes to message 8 then send message 10 to Group 3. This would allow us to orchestrate a workflow so that we can repeat the show over and over without a director manning every message.

**Comment by Erioldoesdesign** [comment]
This is like 'tree logic' Theres a visual to support this:
![image](https://user-images.githubusercontent.com/11681324/64695278-a67cf980-d493-11e9-9217-b77e307a34b6.png)
