### ISSUE TITLE
WhatsApp Integration

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/tenfour#169]
From tenfour-archive created by [caharding](https://github.com/caharding): ushahidi/tenfour-archive#1392  

User wants to send check-ins over WhatsApp.

[Nexmo](https://www.nexmo.com/blog/2018/08/01/nexmo-apis-elevate-customer-experiences-whatsapp-business/) and [Twilio](https://www.twilio.com/whatsapp) have documentation on their approaches. @mackers could we get a 1hr investigation into specing feasibility and time? 

I've requested Nexmo access and will let you know as soon as we have it. 

Issues to open after spec
- [ ] Configure WhatsApp as channel in backend
- [ ] Add WhatsApp to contact type
- [ ] Add WhatsApp to sample  CSV
- [ ] Add WhatsApp as Import field in CSV upload
- [ ] Add WhatsApp to Channel config
- [ ] Add WhatsApp to "send via" in compose flow

**Comment by CeciliaHinga** [comment]
Should be trivial to implement using Twilio's API. Presume same for Nexmo.

I estimate 5 days effort to get a v1.0 of this feature with full 2-way communication on par with SMS channel comms.

I would venture that the most difficult part is pricing correctly, as for some reason, whatsapp message pricing is vastly different per country. 

@caharding Not sure why we need a new contact type or CSV columns? Surely we just send a WhatsApp message to the user's phone number. If orgs have to maintain separate contacts then user management effort will surely be doubled?

**Comment by CeciliaHinga** [comment]
Should we use our contacts in Twilio that we met earlier this year to chase this?

---------- Forwarded message ---------
From: Bobbi Jo Price <bobbijo@twilio.com>
CC: Erika Balbuena <ebalbuena@twilio.com>, 
Jacob Talbot <jtalbot@twilio.com>

**Comment by CeciliaHinga** [comment]
Nothing yet
-- 
Charlie Harding
Product Director

**Comment by CeciliaHinga** [comment]
Yeah do you know who made them?

**Comment by CeciliaHinga** [comment]
@caharding Have you heard anything from Nexmo on this?

**Comment by CeciliaHinga** [comment]
Linda, Nat and I were in the meeting.
