### ISSUE TITLE
Request Help / Manual Check-ins / Help Button #860

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/tenfour#66]
A user wants to be able to manually check-in. That is to say, if they have landed safely in a new city, they want to go to Check-in to say "I'm OK" even if someone hasn't asked them for a response. Likewise, they need a way of saying "I need help" without a question having gone out to them. We've heard this need from a number of testers that we've spoken to.

**Main Issues**

_Requester_

  

- [ ] As a user I want to be able to send my organization an alert that I need help
- [ ]   As a user I want to be able to provide more info about what help I need in a message
- [ ]   As a user I want to send my location
- [ ]   As a user I want to be able to set a "status" of severity of my request (I'm OK, Unsure, Need help, Need Urgent help)
- [ ]   As a user I want to be able to share/broadcast my request for help to many people on many channels even outside of my org (share button)
- [ ]   As a user I want to be able to change my status to OK once I'm OK

_Admin_

  

- [ ] As an admin I want to receive an alert when someone has requested help
- [ ]   As an admin I want to see a list of of all requests for help that have come in
- [ ]   As an admin I want to be able to set the status of the response (New issue, In Progress, Resolved)
- [ ]   As an admin I want my list of all requests for help to be sortable, and I want the most urgent and new issues to stand out
- [ ]   As ad admin I want to be able to share a request for help with another person
- [ ]   As an admin I want to be able to know who is working on a request for help
![image](https://user-images.githubusercontent.com/20906968/63847941-7f083600-c997-11e9-84de-9fcb1b241bc3.png)
