### ISSUE TITLE
Location based Check Ins #870

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/tenfour#68]
- [ ] Users need to be able to use location services to be able to send and receive Check-ins
- [ ]   User wants to be able to broadcast location if they need help
- [ ]   User wants to be able to author a check in within a bounded geography
- [ ]   User wants to view all check in replies on a map
- [ ]   User wants each check- in to have a map
- [ ]   User wants for each check-in the ability to look at a map of where 1 person is
- [ ]   User wants each person to have a map of historical check ins
- [ ]   User wants a complete organization map across all check-ins and people that can be viewable at different time periods

Locations can be viewed as multiple types

- [ ]   A path
- [ ]   An office or home address
- [ ]   A POI
- [ ]   A city
- [ ]   A county / province / state / country

**Comment by CeciliaHinga** [comment]
Early design sketches
