### ISSUE TITLE
 Internationalization Toolkit #872

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/tenfour#69]
Every time we need to add a new country there are a bunch of things that need to be done.

 

- [ ]  Purchase new numbers
- [ ]   Configure new numbers
- [ ]   Update country settings
- [ ]   Configure servers
- [ ]   Translate the app
- [ ]   Update pricing
- [ ]   Update marketing materials

We need to build tools that make this easier
